[params]
  keywords = "Vorsatzpapiere, Ornamente, Papier, BÃ¼cher, Book end paper, paper, books"
  copyrightYears = "MMXXI - MMXXVI"
  cc = true
  stylesheets = []
  iiifCanvasHeight = 400
  iiifCanvasWidth = 300
  productionIIIFURLPrefix="https://static.projektemacher.org/vorsatzpapier/"
  disableScale = true
  description = "Old endpapers and wallpapers"
  wikidata = true
  debug = true

  [params.preview]
    outputPrefix = "ogPreview"
    outputSuffix = ".png"
    format =  "svg"
    image = "front.jpg"
    source = "overlay"
    [params.preview.size]
      height = 630
      width = 1200
    [params.preview.svg]
      template = "./Source Files/Other/preview-template.svg"
      removeMissing = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
